pipeline {
    agent any
    options {
        timeout(time:1, unit:'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('terraform initialize') {
            steps {
                sh '''
                  cd 01-VPC
                  terraform init
                '''
            }
        }
        stage('plan') {
            steps {
                sh '''
                  cd 01-VPC
                  terraform plan
                '''
            }
        }
        stage('apply') {
            steps {
                sh '''
                  cd 01-VPC
                  terraform destroy -auto-approve
                '''
            }
        }
    }
}
